spring:
  datasource:
    password: 123456
    url: jdbc:mysql://localhost:3306/controle_financeiro
    username: root
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        format_sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    pathmatch:      matching-strategy: ant-path-matcher
        
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true 

finances:
  jwt:
    secret: rm!@N=Ke!~p8VTA2ZRK~nMDQX5Uvm!mD&]{@Vr?G;2?XhbC:Qa#9#eMLN\}x3?JR3.2zr~v)gYF^8\:8>:XfB:Ww75N/emt9Yj[bQMNCWwW\J?N,nvH.<2\.r~w]*e~vgak)X"v8H`MH/7"2E`,^k@n<vE-wD3g9JWPy;CrY*.Kd2_D])=><D?YhBaSua5hW%{2]_FVXzb9`8FH^b[X3jzVER&:jw2<=c38=>L/zBq`}C6tT*cCSVC^c]-L}&/
    expiration: 86400000
    
info:
  app:
    name: "@project.name@"
    version: "@project.version@"
    groupId: "@project.groupId@"
    java:
      source: "@java.version@"
      target: "@java.version@"
